FROM langflowai/langflow:latest

USER root

RUN apt-get update --allow-releaseinfo-change && \
    apt-get upgrade -y && \
    apt-get install -y build-essential curl npm git && \
    apt-get clean


CMD ["python", "-m", "langflow", "run", "--host", "0.0.0.0", "--port", "8080"]
