FROM langflowai/langflow:1.5.0

USER root

RUN apt-get update --allow-releaseinfo-change && \
    apt-get upgrade -y && \
    apt-get install -y build-essential curl git graphviz && \
    # Install Node.js and npm using NodeSource
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    # Verify installations
    node -v && \
    npm -v && \
    apt-get clean

CMD ["python", "-m", "langflow", "run", "--host", "0.0.0.0", "--port", "8080"]
